name: Java CI with Coverage

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'  # Adjust to your version
        distribution: 'temurin'
    
    - name: Run tests with coverage
      run: mvn clean test
    
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: ../badges
        generate-branches-badge: true
        generate-summary: true
    
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    
    - name: Commit and push badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd .github/badges
        if [[ `git status --porcelain` ]]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.svg
          git commit -m "Update coverage badges"
          git push
        fi